---

- hosts: all
  remote_user: ansible
  become: true

  tasks:
    - name: Create user
      user:
        name: mo
        createhome: yes
        uid: 1337
        state: present
        shell: /bin/bash

    - name: Copy SSH key
      authorized_key:
        user: mo
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        key_options: 'no-port-forwarding'

    - name: Add user to sudoers
      copy:
        dest: /etc/sudoers.d/mo
        content: 'mo ALL= NOPASSWD: ALL'
        owner: root
        group: root
        mode: 0500

