---
- name: Create Ansible user
  hosts: testubuntu1
  remote_user: itadmin
  become: true
  tasks:

  - name: Create Ansible group
    group:
      name: ansible
      gid: 20000
      state: present

  - name: Create user Ansible
    user:
      name: ansible
      createhome: yes
      uid: 20000
      group: ansible
      state: present

  - name: Copy SSH key
    authorized_key:
      user: ansible
      key: "{{ lookup('file', './ssh/id_rsa.pub') }}"
      key_options: 'no-port-forwarding'

  - name: Install Sudo
    package:
      name: sudo
      state: present

  - name: Add ansible user to sudoers
    copy:
      dest: /etc/sudoers.d/ansible
      content: 'ansible ALL= NOPASSWD: ALL'
      owner: root
      group: root
      mode: 0500
      
  - name: Create user
    user:
      name: mo
      createhome: yes
      uid: 1337
      state: present
      shell: /bin/bash

  - name: Copy SSH key
    authorized_key:
      user: mo
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      key_options: 'no-port-forwarding'

  - name: Add user to sudoers
    copy:
      dest: /etc/sudoers.d/mo
      content: 'mo ALL= NOPASSWD: ALL'
      owner: root
      group: root
      mode: 0500

